### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by weihuang527** [funkey/mala#2]
Four datasets appear in the code, they are "sample_A_padded_20160501.aligned.filled.cropped", "sample_B_padded_20160501.aligned.filled.cropped", "sample_C_padded_20160501.aligned.filled.cropped.0:90" and "sample_ABC_padded_20160501.defects.hdf", respectively. I want to ask what they are, they don't appear on CREMI web. Are they the data generated by some sort of processing of the raw datasets? 
Thanks!

**Comment by funkey** [comment]
The "aligned" datasets are our re-registered versions of the CREMI training volumes, see the [archive](http://cremi.org/static/data/20170312_mala_v2.tar.gz) we made public.

The "defects" dataset is a new dataset that we did not use for our MALA submission, but for subsequent experiments. It contains examples of common artifacts found int the official training data (support film folds, staining residuals). We randomly add those artifacts to training batches, using the gunpowder `DefefctAugment` node.
