### ISSUE TITLE
What's the file 'net_io_names.json' in train_until.py?

### ISSUE THREAD

**Issue by HuXiaoling** [funkey/mala#3]
In train_until.py, we are supposed to load one .json file: [https://github.com/funkey/mala/blob/master/scripts/train_until.py#L19](https://github.com/funkey/mala/blob/master/scripts/train_until.py#L19)

So, I'd like to know what the file 'net_io_names.json' is?

**Comment by funkey** [comment]
The JSON is generated by the `mknet.py` [script](https://github.com/funkey/mala/blob/master/scripts/mknet.py#L49), which you have to run before starting the training.
